gText_Birch_Welcome::
	.string "Hallo!\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Willkomen in POKEMON SMARAGD ROGUE!\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "In diesem Spiel \n"
	.string "ist jedes Abenteuer,...\p"
	.string "jeder Ort und jedes POKEMON,\n"
	.string "das du triffst, einzigartig!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Nun...\n"
	.string "erzähle etwas von dir$"
	.string "$"

gText_Birch_BoyOrGirl::
	.string "Wähle eine Figur$"

gText_Birch_AvatarStyle0::
	.string "Wähle ein Aussehen$"

gText_Birch_AvatarStyle1::
	.string "Wähle einen Kleidungsstil$"

gText_Birch_WhatsYourName::
	.string "Wie ist dein Name?$"

gText_Birch_HappyWithAvatar::
	.string "So siehst du aus?\n$"

gText_Birch_SoItsPlayer::
	.string "Du heißt {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Oh, okay!\p"
	.string "{PLAYER}{KUN}!"
	.string "$"

gText_Birch_AreYouReady::
	.string "Ich warte auf dich im LABOR!\p"
	.string "Besuch mich, sobald du ankommst.\p"
	.string "$"
